[system]
compatible=@RAUC_COMPATIBLE@
bootloader=@BOOTLOADER@
data-directory=/data/rauc

[keyring]
path=/etc/rauc/keyring.pem

[handlers]
post-install=/usr/lib/rauc/post-install.sh

[slot.rootfs.0]
device=/dev/disk/by-partlabel/rootfs-a
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-partlabel/rootfs-b
type=ext4
bootname=B
